export * from './lib/customer.module';
export * from './lib/customer.service';
export * from './lib/customer.resolver';
export * from './lib/customer-auth.resolver';
export * from './lib/customer-magic-link.resolver';
export * from './lib/customer-oauth.resolver';
export * from './lib/customer-role.service';
export * from './lib/customer-role.resolver';
export * from './lib/dto';
